version: "3.8"
services:
  db:
    container_name: db
    image: postgres:14.5-alpine
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]

    environment:
      - POSTGRES_DB=transteven
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  multiplaylist-server:
    container_name: multiplaylist-server
    image: multiplaylist-server
    build: server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8443:8443
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/api/health"]

  multiplaylist-frontend:
    container_name: multiplaylist-frontend
    image: multiplaylist-frontend
    build: frontend
    args:
      api_base_url: http://localhost:8088
    ports:
      - "3000:3000"
    depends_on:
      - multiplaylist-server
    restart: always
