version: "3.8"
services:
  db:
    image: postgres:14.5-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=transteven
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
      - db:/data/postgres

  multiplaylist-backend:
    container_name: multiplaylist-backend
    image: transteven/multiplaylist-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user
    ports:
      - 8443:8443
    depends_on:
      - db
    networks:
      - db
    restart: always
  multiplaylist-frontend:
    container_name: multiplaylist-frontend
    image: transteven/multiplaylist-frontend
    build:
      context: multiplaylist/client
    args:
      api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - multiplaylist-backend
    restart: always

  networks:
    db:
      driver: bridge

  volumes:
    db:
