version: "3.8"
services:
  db:
    container_name: db
    image: postgres:14.5-alpine
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "transteven", "-U", "postgres"]
    environment:
      - PGUSER=postgres
      - POSTGRES_DB=transteven
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  multiplaylist-server:
    container_name: multiplaylist-server
    image: multiplaylist-server
    build:
      context: server
      dockerfile: server.dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8443:8443
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/api/health"]

  multiplaylist-frontend:
    container_name: multiplaylist-frontend
    image: multiplaylist-frontend
    build:
      context: client
      dockerfile: client.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - multiplaylist-server
