version: "3.8"
services:
  db:
    image: postgres:14.5-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=transteven
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

  transteven:
    build: ./
    container_name: transteven
    environment:
      - DB_SERVER:db
      - POSTGRES_DB=transteven
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8443:8443
    depends_on:
      - db
volumes:
  postgres_data:
